apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nw1zrusbz-nodejs
  janus-idp.io/tekton: nw1zrusbz-nodejs
  backstage.io/kubernetes-id: nw1zrusbz-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nw1zrusbz-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
